// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:         string;
  type:       string;
  place_type: string[];
  relevance:  number;
  properties: Properties;
  text:       string;
  place_name: string;
  center:     number[];
  geometry:   Geometry;
  address?:   string;
  context:    Context[];
}

export interface Context {
  id:          string;
  text:        string;
  wikidata?:   Wikidata;
  short_code?: ShortCode;
}

export enum ShortCode {
  MX = "mx",
  MXDur = "MX-DUR",
}

export enum Wikidata {
  Q112813 = "Q112813",
  Q79918 = "Q79918",
  Q96 = "Q96",
}

export interface Geometry {
  type:          string;
  coordinates:   number[];
  interpolated?: boolean;
  omitted?:      boolean;
}

export interface Properties {
  accuracy: string;
}
